### ISSUE TITLE
Non-automated change log

### ISSUE THREAD

**Issue by killercup** [crate-ci/crate-ci.github.io#5]
The book currently mentions clog. As a manual alternative, I like using <http://keepachangelog.com>. A nice side-effect is that it adds a user-focused description of what's changed to every PR.

**Comment by epage** [comment]
I think this is reasonable.  I know @CAD97 is also in favor of this.

Kind of fun that the reason I got started with clog is [your blog post](https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/).  How come you have switched away from it?

Also, my hope was to have discussions like this on [meta](https://github.com/crate-ci/meta/issues).    I tried to call this out on the front page of the site

> Contributing
> -  Find a mistake or out of date examples? Feel free to file an issue or create a PR.
> -  Have a way to improve the CI for crates? Feel free to join the discussion

Any suggestions on how I could improve this?

**Comment by killercup** [comment]
> Also, my hope was to have discussions like this on meta.

Oh, sorry! I'll open a new issue there and answer your (non-meta, lol) remarks there as well.

> Any suggestions on how I could improve this?

Haha, you got me, I didn't bother reading the text on the front page… (because in 99% of the cases it's just the usual blub about what this book is about)

If there are more people who are as bad at this as I am, you might want to (a) make "Contributing" a headline, but more importantly, (b) add an issue template so I see it again when opening an issue.

**Comment by epage** [comment]
Thanks! Fixed the headline and created #6 and #7
